# pylint: disable=line-too-long,useless-suppression
# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
from collections.abc import MutableMapping
from io import IOBase
from typing import Any, Callable, IO, Optional, TypeVar, Union, overload

from azure.core import PipelineClient
from azure.core.exceptions import (
    ClientAuthenticationError,
    HttpResponseError,
    ResourceExistsError,
    ResourceNotFoundError,
    ResourceNotModifiedError,
    map_error,
)
from azure.core.pipeline import PipelineResponse
from azure.core.rest import HttpRequest, HttpResponse
from azure.core.tracing.decorator import distributed_trace
from azure.core.utils import case_insensitive_dict

from .. import models as _models
from .._configuration import IotHubGatewayServiceAPIsConfiguration
from .._utils.serialization import Deserializer, Serializer

T = TypeVar("T")
ClsType = Optional[Callable[[PipelineResponse[HttpRequest, HttpResponse], T, dict[str, Any]], Any]]

_SERIALIZER = Serializer()
_SERIALIZER.client_side_validation = False


def build_update_registry_request(**kwargs: Any) -> HttpRequest:
    _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
    _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

    api_version: str = kwargs.pop("api_version", _params.pop("api-version", "2021-04-12"))
    content_type: Optional[str] = kwargs.pop("content_type", _headers.pop("Content-Type", None))
    accept = _headers.pop("Accept", "application/json")

    # Construct URL
    _url = kwargs.pop("template_url", "/devices")

    # Construct parameters
    _params["api-version"] = _SERIALIZER.query("api_version", api_version, "str")

    # Construct headers
    if content_type is not None:
        _headers["Content-Type"] = _SERIALIZER.header("content_type", content_type, "str")
    _headers["Accept"] = _SERIALIZER.header("accept", accept, "str")

    return HttpRequest(method="POST", url=_url, params=_params, headers=_headers, **kwargs)


class BulkRegistryOperations:
    """
    .. warning::
        **DO NOT** instantiate this class directly.

        Instead, you should access the following operations through
        :class:`~azure.iot.hub.protocol.IotHubGatewayServiceAPIs`'s
        :attr:`bulk_registry` attribute.
    """

    models = _models

    def __init__(self, *args, **kwargs) -> None:
        input_args = list(args)
        self._client: PipelineClient = input_args.pop(0) if input_args else kwargs.pop("client")
        self._config: IotHubGatewayServiceAPIsConfiguration = input_args.pop(0) if input_args else kwargs.pop("config")
        self._serialize: Serializer = input_args.pop(0) if input_args else kwargs.pop("serializer")
        self._deserialize: Deserializer = input_args.pop(0) if input_args else kwargs.pop("deserializer")

    @overload
    def update_registry(
        self, devices: list[_models.ExportImportDevice], *, content_type: str = "application/json", **kwargs: Any
    ) -> _models.BulkRegistryOperationResult:
        """Creates, updates, or deletes the identities of multiple devices from the IoT Hub identity
        registry. A device identity can be specified only once in the list. Different operations
        (create, update, delete) on different devices are allowed. A maximum of 100 devices can be
        specified per invocation. For large scale operations, use the import feature using blob storage
        (https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-identity-registry#import-and-export-device-identities).

        :param devices: The registry operations to perform. Required.
        :type devices: list[~azure.iot.hub.protocol.models.ExportImportDevice]
        :keyword content_type: Body Parameter content-type. Content type parameter for JSON body.
         Default value is "application/json".
        :paramtype content_type: str
        :return: BulkRegistryOperationResult or the result of cls(response)
        :rtype: ~azure.iot.hub.protocol.models.BulkRegistryOperationResult
        :raises ~azure.core.exceptions.HttpResponseError:
        """

    @overload
    def update_registry(
        self, devices: IO[bytes], *, content_type: str = "application/json", **kwargs: Any
    ) -> _models.BulkRegistryOperationResult:
        """Creates, updates, or deletes the identities of multiple devices from the IoT Hub identity
        registry. A device identity can be specified only once in the list. Different operations
        (create, update, delete) on different devices are allowed. A maximum of 100 devices can be
        specified per invocation. For large scale operations, use the import feature using blob storage
        (https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-identity-registry#import-and-export-device-identities).

        :param devices: The registry operations to perform. Required.
        :type devices: IO[bytes]
        :keyword content_type: Body Parameter content-type. Content type parameter for binary body.
         Default value is "application/json".
        :paramtype content_type: str
        :return: BulkRegistryOperationResult or the result of cls(response)
        :rtype: ~azure.iot.hub.protocol.models.BulkRegistryOperationResult
        :raises ~azure.core.exceptions.HttpResponseError:
        """

    @distributed_trace
    def update_registry(
        self, devices: Union[list[_models.ExportImportDevice], IO[bytes]], **kwargs: Any
    ) -> _models.BulkRegistryOperationResult:
        """Creates, updates, or deletes the identities of multiple devices from the IoT Hub identity
        registry. A device identity can be specified only once in the list. Different operations
        (create, update, delete) on different devices are allowed. A maximum of 100 devices can be
        specified per invocation. For large scale operations, use the import feature using blob storage
        (https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-identity-registry#import-and-export-device-identities).

        :param devices: The registry operations to perform. Is either a [ExportImportDevice] type or a
         IO[bytes] type. Required.
        :type devices: list[~azure.iot.hub.protocol.models.ExportImportDevice] or IO[bytes]
        :return: BulkRegistryOperationResult or the result of cls(response)
        :rtype: ~azure.iot.hub.protocol.models.BulkRegistryOperationResult
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
        _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

        api_version: str = kwargs.pop("api_version", _params.pop("api-version", self._config.api_version))
        content_type: Optional[str] = kwargs.pop("content_type", _headers.pop("Content-Type", None))
        cls: ClsType[_models.BulkRegistryOperationResult] = kwargs.pop("cls", None)

        content_type = content_type or "application/json"
        _json = None
        _content = None
        if isinstance(devices, (IOBase, bytes)):
            _content = devices
        else:
            _json = self._serialize.body(devices, "[ExportImportDevice]")

        _request = build_update_registry_request(
            api_version=api_version,
            content_type=content_type,
            json=_json,
            content=_content,
            headers=_headers,
            params=_params,
        )
        _request.url = self._client.format_url(_request.url)

        _stream = False
        pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
            _request, stream=_stream, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200, 400]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        deserialized = self._deserialize("BulkRegistryOperationResult", pipeline_response.http_response)

        if cls:
            return cls(pipeline_response, deserialized, {})  # type: ignore

        return deserialized  # type: ignore
