# pylint: disable=too-many-lines
# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
from collections.abc import MutableMapping
from io import IOBase
from typing import Any, Callable, IO, Optional, TypeVar, Union, overload

from azure.core import PipelineClient
from azure.core.exceptions import (
    ClientAuthenticationError,
    HttpResponseError,
    ResourceExistsError,
    ResourceNotFoundError,
    ResourceNotModifiedError,
    map_error,
)
from azure.core.pipeline import PipelineResponse
from azure.core.rest import HttpRequest, HttpResponse
from azure.core.tracing.decorator import distributed_trace
from azure.core.utils import case_insensitive_dict

from .. import models as _models
from .._configuration import IotHubGatewayServiceAPIsConfiguration
from .._utils.serialization import Deserializer, Serializer

T = TypeVar("T")
ClsType = Optional[Callable[[PipelineResponse[HttpRequest, HttpResponse], T, dict[str, Any]], Any]]

_SERIALIZER = Serializer()
_SERIALIZER.client_side_validation = False


def build_get_twin_request(id: str, mid: str, **kwargs: Any) -> HttpRequest:
    _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
    _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

    api_version: str = kwargs.pop("api_version", _params.pop("api-version", "2021-04-12"))
    accept = _headers.pop("Accept", "application/json")

    # Construct URL
    _url = kwargs.pop("template_url", "/twins/{id}/modules/{mid}")
    path_format_arguments = {
        "id": _SERIALIZER.url("id", id, "str"),
        "mid": _SERIALIZER.url("mid", mid, "str"),
    }

    _url: str = _url.format(**path_format_arguments)  # type: ignore

    # Construct parameters
    _params["api-version"] = _SERIALIZER.query("api_version", api_version, "str")

    # Construct headers
    _headers["Accept"] = _SERIALIZER.header("accept", accept, "str")

    return HttpRequest(method="GET", url=_url, params=_params, headers=_headers, **kwargs)


def build_replace_twin_request(id: str, mid: str, *, if_match: Optional[str] = None, **kwargs: Any) -> HttpRequest:
    _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
    _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

    api_version: str = kwargs.pop("api_version", _params.pop("api-version", "2021-04-12"))
    content_type: Optional[str] = kwargs.pop("content_type", _headers.pop("Content-Type", None))
    accept = _headers.pop("Accept", "application/json")

    # Construct URL
    _url = kwargs.pop("template_url", "/twins/{id}/modules/{mid}")
    path_format_arguments = {
        "id": _SERIALIZER.url("id", id, "str"),
        "mid": _SERIALIZER.url("mid", mid, "str"),
    }

    _url: str = _url.format(**path_format_arguments)  # type: ignore

    # Construct parameters
    _params["api-version"] = _SERIALIZER.query("api_version", api_version, "str")

    # Construct headers
    if if_match is not None:
        _headers["If-Match"] = _SERIALIZER.header("if_match", if_match, "str")
    if content_type is not None:
        _headers["Content-Type"] = _SERIALIZER.header("content_type", content_type, "str")
    _headers["Accept"] = _SERIALIZER.header("accept", accept, "str")

    return HttpRequest(method="PUT", url=_url, params=_params, headers=_headers, **kwargs)


def build_update_twin_request(id: str, mid: str, *, if_match: Optional[str] = None, **kwargs: Any) -> HttpRequest:
    _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
    _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

    api_version: str = kwargs.pop("api_version", _params.pop("api-version", "2021-04-12"))
    content_type: Optional[str] = kwargs.pop("content_type", _headers.pop("Content-Type", None))
    accept = _headers.pop("Accept", "application/json")

    # Construct URL
    _url = kwargs.pop("template_url", "/twins/{id}/modules/{mid}")
    path_format_arguments = {
        "id": _SERIALIZER.url("id", id, "str"),
        "mid": _SERIALIZER.url("mid", mid, "str"),
    }

    _url: str = _url.format(**path_format_arguments)  # type: ignore

    # Construct parameters
    _params["api-version"] = _SERIALIZER.query("api_version", api_version, "str")

    # Construct headers
    if if_match is not None:
        _headers["If-Match"] = _SERIALIZER.header("if_match", if_match, "str")
    if content_type is not None:
        _headers["Content-Type"] = _SERIALIZER.header("content_type", content_type, "str")
    _headers["Accept"] = _SERIALIZER.header("accept", accept, "str")

    return HttpRequest(method="PATCH", url=_url, params=_params, headers=_headers, **kwargs)


def build_get_modules_on_device_request(id: str, **kwargs: Any) -> HttpRequest:
    _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
    _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

    api_version: str = kwargs.pop("api_version", _params.pop("api-version", "2021-04-12"))
    accept = _headers.pop("Accept", "application/json")

    # Construct URL
    _url = kwargs.pop("template_url", "/devices/{id}/modules")
    path_format_arguments = {
        "id": _SERIALIZER.url("id", id, "str"),
    }

    _url: str = _url.format(**path_format_arguments)  # type: ignore

    # Construct parameters
    _params["api-version"] = _SERIALIZER.query("api_version", api_version, "str")

    # Construct headers
    _headers["Accept"] = _SERIALIZER.header("accept", accept, "str")

    return HttpRequest(method="GET", url=_url, params=_params, headers=_headers, **kwargs)


def build_get_identity_request(id: str, mid: str, **kwargs: Any) -> HttpRequest:
    _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
    _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

    api_version: str = kwargs.pop("api_version", _params.pop("api-version", "2021-04-12"))
    accept = _headers.pop("Accept", "application/json")

    # Construct URL
    _url = kwargs.pop("template_url", "/devices/{id}/modules/{mid}")
    path_format_arguments = {
        "id": _SERIALIZER.url("id", id, "str"),
        "mid": _SERIALIZER.url("mid", mid, "str"),
    }

    _url: str = _url.format(**path_format_arguments)  # type: ignore

    # Construct parameters
    _params["api-version"] = _SERIALIZER.query("api_version", api_version, "str")

    # Construct headers
    _headers["Accept"] = _SERIALIZER.header("accept", accept, "str")

    return HttpRequest(method="GET", url=_url, params=_params, headers=_headers, **kwargs)


def build_create_or_update_identity_request(
    id: str, mid: str, *, if_match: Optional[str] = None, **kwargs: Any
) -> HttpRequest:
    _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
    _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

    api_version: str = kwargs.pop("api_version", _params.pop("api-version", "2021-04-12"))
    content_type: Optional[str] = kwargs.pop("content_type", _headers.pop("Content-Type", None))
    accept = _headers.pop("Accept", "application/json")

    # Construct URL
    _url = kwargs.pop("template_url", "/devices/{id}/modules/{mid}")
    path_format_arguments = {
        "id": _SERIALIZER.url("id", id, "str"),
        "mid": _SERIALIZER.url("mid", mid, "str"),
    }

    _url: str = _url.format(**path_format_arguments)  # type: ignore

    # Construct parameters
    _params["api-version"] = _SERIALIZER.query("api_version", api_version, "str")

    # Construct headers
    if if_match is not None:
        _headers["If-Match"] = _SERIALIZER.header("if_match", if_match, "str")
    if content_type is not None:
        _headers["Content-Type"] = _SERIALIZER.header("content_type", content_type, "str")
    _headers["Accept"] = _SERIALIZER.header("accept", accept, "str")

    return HttpRequest(method="PUT", url=_url, params=_params, headers=_headers, **kwargs)


def build_delete_identity_request(id: str, mid: str, *, if_match: Optional[str] = None, **kwargs: Any) -> HttpRequest:
    _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
    _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

    api_version: str = kwargs.pop("api_version", _params.pop("api-version", "2021-04-12"))
    # Construct URL
    _url = kwargs.pop("template_url", "/devices/{id}/modules/{mid}")
    path_format_arguments = {
        "id": _SERIALIZER.url("id", id, "str"),
        "mid": _SERIALIZER.url("mid", mid, "str"),
    }

    _url: str = _url.format(**path_format_arguments)  # type: ignore

    # Construct parameters
    _params["api-version"] = _SERIALIZER.query("api_version", api_version, "str")

    # Construct headers
    if if_match is not None:
        _headers["If-Match"] = _SERIALIZER.header("if_match", if_match, "str")

    return HttpRequest(method="DELETE", url=_url, params=_params, headers=_headers, **kwargs)


def build_invoke_method_request(device_id: str, module_id: str, **kwargs: Any) -> HttpRequest:
    _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
    _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

    api_version: str = kwargs.pop("api_version", _params.pop("api-version", "2021-04-12"))
    content_type: Optional[str] = kwargs.pop("content_type", _headers.pop("Content-Type", None))
    accept = _headers.pop("Accept", "application/json")

    # Construct URL
    _url = kwargs.pop("template_url", "/twins/{deviceId}/modules/{moduleId}/methods")
    path_format_arguments = {
        "deviceId": _SERIALIZER.url("device_id", device_id, "str"),
        "moduleId": _SERIALIZER.url("module_id", module_id, "str"),
    }

    _url: str = _url.format(**path_format_arguments)  # type: ignore

    # Construct parameters
    _params["api-version"] = _SERIALIZER.query("api_version", api_version, "str")

    # Construct headers
    if content_type is not None:
        _headers["Content-Type"] = _SERIALIZER.header("content_type", content_type, "str")
    _headers["Accept"] = _SERIALIZER.header("accept", accept, "str")

    return HttpRequest(method="POST", url=_url, params=_params, headers=_headers, **kwargs)


class ModulesOperations:
    """
    .. warning::
        **DO NOT** instantiate this class directly.

        Instead, you should access the following operations through
        :class:`~azure.iot.hub.protocol.IotHubGatewayServiceAPIs`'s
        :attr:`modules` attribute.
    """

    models = _models

    def __init__(self, *args, **kwargs) -> None:
        input_args = list(args)
        self._client: PipelineClient = input_args.pop(0) if input_args else kwargs.pop("client")
        self._config: IotHubGatewayServiceAPIsConfiguration = input_args.pop(0) if input_args else kwargs.pop("config")
        self._serialize: Serializer = input_args.pop(0) if input_args else kwargs.pop("serializer")
        self._deserialize: Deserializer = input_args.pop(0) if input_args else kwargs.pop("deserializer")

    @distributed_trace
    def get_twin(self, id: str, mid: str, **kwargs: Any) -> _models.Twin:
        """Gets the module twin. See
        https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-device-twins for more information.

        :param id: The unique identifier of the device. Required.
        :type id: str
        :param mid: The unique identifier of the module. Required.
        :type mid: str
        :return: Twin or the result of cls(response)
        :rtype: ~azure.iot.hub.protocol.models.Twin
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = kwargs.pop("headers", {}) or {}
        _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

        api_version: str = kwargs.pop("api_version", _params.pop("api-version", self._config.api_version))
        cls: ClsType[_models.Twin] = kwargs.pop("cls", None)

        _request = build_get_twin_request(
            id=id,
            mid=mid,
            api_version=api_version,
            headers=_headers,
            params=_params,
        )
        _request.url = self._client.format_url(_request.url)

        _stream = False
        pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
            _request, stream=_stream, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        deserialized = self._deserialize("Twin", pipeline_response.http_response)

        if cls:
            return cls(pipeline_response, deserialized, {})  # type: ignore

        return deserialized  # type: ignore

    @overload
    def replace_twin(
        self,
        id: str,
        mid: str,
        device_twin_info: _models.Twin,
        if_match: Optional[str] = None,
        *,
        content_type: str = "application/json",
        **kwargs: Any
    ) -> _models.Twin:
        """Replaces the tags and desired properties of a module twin. See
        https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-device-twins for more information.

        :param id: The unique identifier of the device. Required.
        :type id: str
        :param mid: The unique identifier of the module. Required.
        :type mid: str
        :param device_twin_info: The module twin info that will replace the existing info. Required.
        :type device_twin_info: ~azure.iot.hub.protocol.models.Twin
        :param if_match: The string representing a weak ETag for the device twin, as per RFC7232. It
         determines if the replace operation should be carried out. Default value is None.
        :type if_match: str
        :keyword content_type: Body Parameter content-type. Content type parameter for JSON body.
         Default value is "application/json".
        :paramtype content_type: str
        :return: Twin or the result of cls(response)
        :rtype: ~azure.iot.hub.protocol.models.Twin
        :raises ~azure.core.exceptions.HttpResponseError:
        """

    @overload
    def replace_twin(
        self,
        id: str,
        mid: str,
        device_twin_info: IO[bytes],
        if_match: Optional[str] = None,
        *,
        content_type: str = "application/json",
        **kwargs: Any
    ) -> _models.Twin:
        """Replaces the tags and desired properties of a module twin. See
        https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-device-twins for more information.

        :param id: The unique identifier of the device. Required.
        :type id: str
        :param mid: The unique identifier of the module. Required.
        :type mid: str
        :param device_twin_info: The module twin info that will replace the existing info. Required.
        :type device_twin_info: IO[bytes]
        :param if_match: The string representing a weak ETag for the device twin, as per RFC7232. It
         determines if the replace operation should be carried out. Default value is None.
        :type if_match: str
        :keyword content_type: Body Parameter content-type. Content type parameter for binary body.
         Default value is "application/json".
        :paramtype content_type: str
        :return: Twin or the result of cls(response)
        :rtype: ~azure.iot.hub.protocol.models.Twin
        :raises ~azure.core.exceptions.HttpResponseError:
        """

    @distributed_trace
    def replace_twin(
        self,
        id: str,
        mid: str,
        device_twin_info: Union[_models.Twin, IO[bytes]],
        if_match: Optional[str] = None,
        **kwargs: Any
    ) -> _models.Twin:
        """Replaces the tags and desired properties of a module twin. See
        https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-device-twins for more information.

        :param id: The unique identifier of the device. Required.
        :type id: str
        :param mid: The unique identifier of the module. Required.
        :type mid: str
        :param device_twin_info: The module twin info that will replace the existing info. Is either a
         Twin type or a IO[bytes] type. Required.
        :type device_twin_info: ~azure.iot.hub.protocol.models.Twin or IO[bytes]
        :param if_match: The string representing a weak ETag for the device twin, as per RFC7232. It
         determines if the replace operation should be carried out. Default value is None.
        :type if_match: str
        :return: Twin or the result of cls(response)
        :rtype: ~azure.iot.hub.protocol.models.Twin
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
        _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

        api_version: str = kwargs.pop("api_version", _params.pop("api-version", self._config.api_version))
        content_type: Optional[str] = kwargs.pop("content_type", _headers.pop("Content-Type", None))
        cls: ClsType[_models.Twin] = kwargs.pop("cls", None)

        content_type = content_type or "application/json"
        _json = None
        _content = None
        if isinstance(device_twin_info, (IOBase, bytes)):
            _content = device_twin_info
        else:
            _json = self._serialize.body(device_twin_info, "Twin")

        _request = build_replace_twin_request(
            id=id,
            mid=mid,
            if_match=if_match,
            api_version=api_version,
            content_type=content_type,
            json=_json,
            content=_content,
            headers=_headers,
            params=_params,
        )
        _request.url = self._client.format_url(_request.url)

        _stream = False
        pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
            _request, stream=_stream, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        deserialized = self._deserialize("Twin", pipeline_response.http_response)

        if cls:
            return cls(pipeline_response, deserialized, {})  # type: ignore

        return deserialized  # type: ignore

    @overload
    def update_twin(
        self,
        id: str,
        mid: str,
        device_twin_info: _models.Twin,
        if_match: Optional[str] = None,
        *,
        content_type: str = "application/json",
        **kwargs: Any
    ) -> _models.Twin:
        """Updates the tags and desired properties of a module twin. See
        https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-device-twins for more information.

        :param id: The unique identifier of the device. Required.
        :type id: str
        :param mid: The unique identifier of the module. Required.
        :type mid: str
        :param device_twin_info: The module twin info containing the tags and desired properties to be
         updated. Required.
        :type device_twin_info: ~azure.iot.hub.protocol.models.Twin
        :param if_match: The string representing a weak ETag for the device twin, as per RFC7232. It
         determines if the update operation should be carried out. Default value is None.
        :type if_match: str
        :keyword content_type: Body Parameter content-type. Content type parameter for JSON body.
         Default value is "application/json".
        :paramtype content_type: str
        :return: Twin or the result of cls(response)
        :rtype: ~azure.iot.hub.protocol.models.Twin
        :raises ~azure.core.exceptions.HttpResponseError:
        """

    @overload
    def update_twin(
        self,
        id: str,
        mid: str,
        device_twin_info: IO[bytes],
        if_match: Optional[str] = None,
        *,
        content_type: str = "application/json",
        **kwargs: Any
    ) -> _models.Twin:
        """Updates the tags and desired properties of a module twin. See
        https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-device-twins for more information.

        :param id: The unique identifier of the device. Required.
        :type id: str
        :param mid: The unique identifier of the module. Required.
        :type mid: str
        :param device_twin_info: The module twin info containing the tags and desired properties to be
         updated. Required.
        :type device_twin_info: IO[bytes]
        :param if_match: The string representing a weak ETag for the device twin, as per RFC7232. It
         determines if the update operation should be carried out. Default value is None.
        :type if_match: str
        :keyword content_type: Body Parameter content-type. Content type parameter for binary body.
         Default value is "application/json".
        :paramtype content_type: str
        :return: Twin or the result of cls(response)
        :rtype: ~azure.iot.hub.protocol.models.Twin
        :raises ~azure.core.exceptions.HttpResponseError:
        """

    @distributed_trace
    def update_twin(
        self,
        id: str,
        mid: str,
        device_twin_info: Union[_models.Twin, IO[bytes]],
        if_match: Optional[str] = None,
        **kwargs: Any
    ) -> _models.Twin:
        """Updates the tags and desired properties of a module twin. See
        https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-device-twins for more information.

        :param id: The unique identifier of the device. Required.
        :type id: str
        :param mid: The unique identifier of the module. Required.
        :type mid: str
        :param device_twin_info: The module twin info containing the tags and desired properties to be
         updated. Is either a Twin type or a IO[bytes] type. Required.
        :type device_twin_info: ~azure.iot.hub.protocol.models.Twin or IO[bytes]
        :param if_match: The string representing a weak ETag for the device twin, as per RFC7232. It
         determines if the update operation should be carried out. Default value is None.
        :type if_match: str
        :return: Twin or the result of cls(response)
        :rtype: ~azure.iot.hub.protocol.models.Twin
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
        _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

        api_version: str = kwargs.pop("api_version", _params.pop("api-version", self._config.api_version))
        content_type: Optional[str] = kwargs.pop("content_type", _headers.pop("Content-Type", None))
        cls: ClsType[_models.Twin] = kwargs.pop("cls", None)

        content_type = content_type or "application/json"
        _json = None
        _content = None
        if isinstance(device_twin_info, (IOBase, bytes)):
            _content = device_twin_info
        else:
            _json = self._serialize.body(device_twin_info, "Twin")

        _request = build_update_twin_request(
            id=id,
            mid=mid,
            if_match=if_match,
            api_version=api_version,
            content_type=content_type,
            json=_json,
            content=_content,
            headers=_headers,
            params=_params,
        )
        _request.url = self._client.format_url(_request.url)

        _stream = False
        pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
            _request, stream=_stream, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        deserialized = self._deserialize("Twin", pipeline_response.http_response)

        if cls:
            return cls(pipeline_response, deserialized, {})  # type: ignore

        return deserialized  # type: ignore

    @distributed_trace
    def get_modules_on_device(self, id: str, **kwargs: Any) -> list[_models.Module]:
        """Gets all the module identities on the device.

        :param id: The unique identifier of the device. Required.
        :type id: str
        :return: list of Module or the result of cls(response)
        :rtype: list[~azure.iot.hub.protocol.models.Module]
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = kwargs.pop("headers", {}) or {}
        _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

        api_version: str = kwargs.pop("api_version", _params.pop("api-version", self._config.api_version))
        cls: ClsType[list[_models.Module]] = kwargs.pop("cls", None)

        _request = build_get_modules_on_device_request(
            id=id,
            api_version=api_version,
            headers=_headers,
            params=_params,
        )
        _request.url = self._client.format_url(_request.url)

        _stream = False
        pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
            _request, stream=_stream, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        deserialized = self._deserialize("[Module]", pipeline_response.http_response)

        if cls:
            return cls(pipeline_response, deserialized, {})  # type: ignore

        return deserialized  # type: ignore

    @distributed_trace
    def get_identity(self, id: str, mid: str, **kwargs: Any) -> _models.Module:
        """Gets a module identity on the device.

        :param id: The unique identifier of the device. Required.
        :type id: str
        :param mid: The unique identifier of the module. Required.
        :type mid: str
        :return: Module or the result of cls(response)
        :rtype: ~azure.iot.hub.protocol.models.Module
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = kwargs.pop("headers", {}) or {}
        _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

        api_version: str = kwargs.pop("api_version", _params.pop("api-version", self._config.api_version))
        cls: ClsType[_models.Module] = kwargs.pop("cls", None)

        _request = build_get_identity_request(
            id=id,
            mid=mid,
            api_version=api_version,
            headers=_headers,
            params=_params,
        )
        _request.url = self._client.format_url(_request.url)

        _stream = False
        pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
            _request, stream=_stream, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        deserialized = self._deserialize("Module", pipeline_response.http_response)

        if cls:
            return cls(pipeline_response, deserialized, {})  # type: ignore

        return deserialized  # type: ignore

    @overload
    def create_or_update_identity(
        self,
        id: str,
        mid: str,
        module: _models.Module,
        if_match: Optional[str] = None,
        *,
        content_type: str = "application/json",
        **kwargs: Any
    ) -> _models.Module:
        """Creates or updates the module identity for a device in the IoT Hub. The moduleId and
        generationId cannot be updated by the user.

        :param id: The unique identifier of the device. Required.
        :type id: str
        :param mid: The unique identifier of the module. Required.
        :type mid: str
        :param module: The module identity. Required.
        :type module: ~azure.iot.hub.protocol.models.Module
        :param if_match: The string representing a weak ETag for the module, as per RFC7232. This
         should not be set when creating a module, but may be set when updating a module. Default value
         is None.
        :type if_match: str
        :keyword content_type: Body Parameter content-type. Content type parameter for JSON body.
         Default value is "application/json".
        :paramtype content_type: str
        :return: Module or the result of cls(response)
        :rtype: ~azure.iot.hub.protocol.models.Module
        :raises ~azure.core.exceptions.HttpResponseError:
        """

    @overload
    def create_or_update_identity(
        self,
        id: str,
        mid: str,
        module: IO[bytes],
        if_match: Optional[str] = None,
        *,
        content_type: str = "application/json",
        **kwargs: Any
    ) -> _models.Module:
        """Creates or updates the module identity for a device in the IoT Hub. The moduleId and
        generationId cannot be updated by the user.

        :param id: The unique identifier of the device. Required.
        :type id: str
        :param mid: The unique identifier of the module. Required.
        :type mid: str
        :param module: The module identity. Required.
        :type module: IO[bytes]
        :param if_match: The string representing a weak ETag for the module, as per RFC7232. This
         should not be set when creating a module, but may be set when updating a module. Default value
         is None.
        :type if_match: str
        :keyword content_type: Body Parameter content-type. Content type parameter for binary body.
         Default value is "application/json".
        :paramtype content_type: str
        :return: Module or the result of cls(response)
        :rtype: ~azure.iot.hub.protocol.models.Module
        :raises ~azure.core.exceptions.HttpResponseError:
        """

    @distributed_trace
    def create_or_update_identity(
        self, id: str, mid: str, module: Union[_models.Module, IO[bytes]], if_match: Optional[str] = None, **kwargs: Any
    ) -> _models.Module:
        """Creates or updates the module identity for a device in the IoT Hub. The moduleId and
        generationId cannot be updated by the user.

        :param id: The unique identifier of the device. Required.
        :type id: str
        :param mid: The unique identifier of the module. Required.
        :type mid: str
        :param module: The module identity. Is either a Module type or a IO[bytes] type. Required.
        :type module: ~azure.iot.hub.protocol.models.Module or IO[bytes]
        :param if_match: The string representing a weak ETag for the module, as per RFC7232. This
         should not be set when creating a module, but may be set when updating a module. Default value
         is None.
        :type if_match: str
        :return: Module or the result of cls(response)
        :rtype: ~azure.iot.hub.protocol.models.Module
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
        _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

        api_version: str = kwargs.pop("api_version", _params.pop("api-version", self._config.api_version))
        content_type: Optional[str] = kwargs.pop("content_type", _headers.pop("Content-Type", None))
        cls: ClsType[_models.Module] = kwargs.pop("cls", None)

        content_type = content_type or "application/json"
        _json = None
        _content = None
        if isinstance(module, (IOBase, bytes)):
            _content = module
        else:
            _json = self._serialize.body(module, "Module")

        _request = build_create_or_update_identity_request(
            id=id,
            mid=mid,
            if_match=if_match,
            api_version=api_version,
            content_type=content_type,
            json=_json,
            content=_content,
            headers=_headers,
            params=_params,
        )
        _request.url = self._client.format_url(_request.url)

        _stream = False
        pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
            _request, stream=_stream, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200, 201]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        deserialized = self._deserialize("Module", pipeline_response.http_response)

        if cls:
            return cls(pipeline_response, deserialized, {})  # type: ignore

        return deserialized  # type: ignore

    @distributed_trace
    def delete_identity(  # pylint: disable=inconsistent-return-statements
        self, id: str, mid: str, if_match: Optional[str] = None, **kwargs: Any
    ) -> None:
        """Deletes the module identity for a device in the IoT Hub.

        :param id: The unique identifier of the deivce. Required.
        :type id: str
        :param mid: The unique identifier of the module. Required.
        :type mid: str
        :param if_match: The string representing a weak ETag for the module, as per RFC7232. The delete
         operation is performed only if this ETag matches the value maintained by the server, indicating
         that the module has not been modified since it was last retrieved. To force an unconditional
         delete, set If-Match to the wildcard character (*). Default value is None.
        :type if_match: str
        :return: None or the result of cls(response)
        :rtype: None
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = kwargs.pop("headers", {}) or {}
        _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

        api_version: str = kwargs.pop("api_version", _params.pop("api-version", self._config.api_version))
        cls: ClsType[None] = kwargs.pop("cls", None)

        _request = build_delete_identity_request(
            id=id,
            mid=mid,
            if_match=if_match,
            api_version=api_version,
            headers=_headers,
            params=_params,
        )
        _request.url = self._client.format_url(_request.url)

        _stream = False
        pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
            _request, stream=_stream, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [204]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        if cls:
            return cls(pipeline_response, None, {})  # type: ignore

    @overload
    def invoke_method(
        self,
        device_id: str,
        module_id: str,
        direct_method_request: _models.CloudToDeviceMethod,
        *,
        content_type: str = "application/json",
        **kwargs: Any
    ) -> _models.CloudToDeviceMethodResult:
        """Invokes a direct method on a module of a device. See
        https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-direct-methods for more information.

        :param device_id: The unique identifier of the device. Required.
        :type device_id: str
        :param module_id: The unique identifier of the module. Required.
        :type module_id: str
        :param direct_method_request: The parameters to execute a direct method on the module.
         Required.
        :type direct_method_request: ~azure.iot.hub.protocol.models.CloudToDeviceMethod
        :keyword content_type: Body Parameter content-type. Content type parameter for JSON body.
         Default value is "application/json".
        :paramtype content_type: str
        :return: CloudToDeviceMethodResult or the result of cls(response)
        :rtype: ~azure.iot.hub.protocol.models.CloudToDeviceMethodResult
        :raises ~azure.core.exceptions.HttpResponseError:
        """

    @overload
    def invoke_method(
        self,
        device_id: str,
        module_id: str,
        direct_method_request: IO[bytes],
        *,
        content_type: str = "application/json",
        **kwargs: Any
    ) -> _models.CloudToDeviceMethodResult:
        """Invokes a direct method on a module of a device. See
        https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-direct-methods for more information.

        :param device_id: The unique identifier of the device. Required.
        :type device_id: str
        :param module_id: The unique identifier of the module. Required.
        :type module_id: str
        :param direct_method_request: The parameters to execute a direct method on the module.
         Required.
        :type direct_method_request: IO[bytes]
        :keyword content_type: Body Parameter content-type. Content type parameter for binary body.
         Default value is "application/json".
        :paramtype content_type: str
        :return: CloudToDeviceMethodResult or the result of cls(response)
        :rtype: ~azure.iot.hub.protocol.models.CloudToDeviceMethodResult
        :raises ~azure.core.exceptions.HttpResponseError:
        """

    @distributed_trace
    def invoke_method(
        self,
        device_id: str,
        module_id: str,
        direct_method_request: Union[_models.CloudToDeviceMethod, IO[bytes]],
        **kwargs: Any
    ) -> _models.CloudToDeviceMethodResult:
        """Invokes a direct method on a module of a device. See
        https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-direct-methods for more information.

        :param device_id: The unique identifier of the device. Required.
        :type device_id: str
        :param module_id: The unique identifier of the module. Required.
        :type module_id: str
        :param direct_method_request: The parameters to execute a direct method on the module. Is
         either a CloudToDeviceMethod type or a IO[bytes] type. Required.
        :type direct_method_request: ~azure.iot.hub.protocol.models.CloudToDeviceMethod or IO[bytes]
        :return: CloudToDeviceMethodResult or the result of cls(response)
        :rtype: ~azure.iot.hub.protocol.models.CloudToDeviceMethodResult
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
        _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

        api_version: str = kwargs.pop("api_version", _params.pop("api-version", self._config.api_version))
        content_type: Optional[str] = kwargs.pop("content_type", _headers.pop("Content-Type", None))
        cls: ClsType[_models.CloudToDeviceMethodResult] = kwargs.pop("cls", None)

        content_type = content_type or "application/json"
        _json = None
        _content = None
        if isinstance(direct_method_request, (IOBase, bytes)):
            _content = direct_method_request
        else:
            _json = self._serialize.body(direct_method_request, "CloudToDeviceMethod")

        _request = build_invoke_method_request(
            device_id=device_id,
            module_id=module_id,
            api_version=api_version,
            content_type=content_type,
            json=_json,
            content=_content,
            headers=_headers,
            params=_params,
        )
        _request.url = self._client.format_url(_request.url)

        _stream = False
        pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
            _request, stream=_stream, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        deserialized = self._deserialize("CloudToDeviceMethodResult", pipeline_response.http_response)

        if cls:
            return cls(pipeline_response, deserialized, {})  # type: ignore

        return deserialized  # type: ignore
