# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
# pylint: disable=wrong-import-position

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ._patch import *  # pylint: disable=unused-wildcard-import

from ._configuration_operations import ConfigurationOperations  # type: ignore
from ._statistics_operations import StatisticsOperations  # type: ignore
from ._devices_operations import DevicesOperations  # type: ignore
from ._bulk_registry_operations import BulkRegistryOperations  # type: ignore
from ._query_operations import QueryOperations  # type: ignore
from ._jobs_operations import JobsOperations  # type: ignore
from ._cloud_to_device_messages_operations import CloudToDeviceMessagesOperations  # type: ignore
from ._modules_operations import ModulesOperations  # type: ignore
from ._digital_twin_operations import DigitalTwinOperations  # type: ignore

from ._patch import __all__ as _patch_all
from ._patch import *
from ._patch import patch_sdk as _patch_sdk

__all__ = [
    "ConfigurationOperations",
    "StatisticsOperations",
    "DevicesOperations",
    "BulkRegistryOperations",
    "QueryOperations",
    "JobsOperations",
    "CloudToDeviceMessagesOperations",
    "ModulesOperations",
    "DigitalTwinOperations",
]
__all__.extend([p for p in _patch_all if p not in __all__])  # pyright: ignore
_patch_sdk()
