# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
from collections.abc import MutableMapping
from io import IOBase
from typing import Any, Callable, IO, Optional, TypeVar, Union, overload

from azure.core import AsyncPipelineClient
from azure.core.exceptions import (
    ClientAuthenticationError,
    HttpResponseError,
    ResourceExistsError,
    ResourceNotFoundError,
    ResourceNotModifiedError,
    map_error,
)
from azure.core.pipeline import PipelineResponse
from azure.core.rest import AsyncHttpResponse, HttpRequest
from azure.core.tracing.decorator_async import distributed_trace_async
from azure.core.utils import case_insensitive_dict

from ... import models as _models
from ..._utils.serialization import Deserializer, Serializer
from ...operations._configuration_operations import (
    build_apply_on_edge_device_request,
    build_create_or_update_request,
    build_delete_request,
    build_get_configurations_request,
    build_get_request,
    build_test_queries_request,
)
from .._configuration import IotHubGatewayServiceAPIsConfiguration

T = TypeVar("T")
ClsType = Optional[Callable[[PipelineResponse[HttpRequest, AsyncHttpResponse], T, dict[str, Any]], Any]]


class ConfigurationOperations:
    """
    .. warning::
        **DO NOT** instantiate this class directly.

        Instead, you should access the following operations through
        :class:`~azure.iot.hub.protocol.aio.IotHubGatewayServiceAPIs`'s
        :attr:`configuration` attribute.
    """

    models = _models

    def __init__(self, *args, **kwargs) -> None:
        input_args = list(args)
        self._client: AsyncPipelineClient = input_args.pop(0) if input_args else kwargs.pop("client")
        self._config: IotHubGatewayServiceAPIsConfiguration = input_args.pop(0) if input_args else kwargs.pop("config")
        self._serialize: Serializer = input_args.pop(0) if input_args else kwargs.pop("serializer")
        self._deserialize: Deserializer = input_args.pop(0) if input_args else kwargs.pop("deserializer")

    @distributed_trace_async
    async def get(self, id: str, **kwargs: Any) -> _models.Configuration:
        """Gets a configuration on the IoT Hub for automatic device/module management.

        :param id: The unique identifier of the configuration. Required.
        :type id: str
        :return: Configuration or the result of cls(response)
        :rtype: ~azure.iot.hub.protocol.models.Configuration
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = kwargs.pop("headers", {}) or {}
        _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

        api_version: str = kwargs.pop("api_version", _params.pop("api-version", self._config.api_version))
        cls: ClsType[_models.Configuration] = kwargs.pop("cls", None)

        _request = build_get_request(
            id=id,
            api_version=api_version,
            headers=_headers,
            params=_params,
        )
        _request.url = self._client.format_url(_request.url)

        _stream = False
        pipeline_response: PipelineResponse = await self._client._pipeline.run(  # pylint: disable=protected-access
            _request, stream=_stream, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        deserialized = self._deserialize("Configuration", pipeline_response.http_response)

        if cls:
            return cls(pipeline_response, deserialized, {})  # type: ignore

        return deserialized  # type: ignore

    @overload
    async def create_or_update(
        self,
        id: str,
        configuration: _models.Configuration,
        if_match: Optional[str] = None,
        *,
        content_type: str = "application/json",
        **kwargs: Any
    ) -> _models.Configuration:
        """Creates or updates a configuration on the IoT Hub for automatic device/module management.
        Configuration identifier and Content cannot be updated.

        :param id: The unique identifier of the configuration. Required.
        :type id: str
        :param configuration: The configuration to be created or updated. Required.
        :type configuration: ~azure.iot.hub.protocol.models.Configuration
        :param if_match: The string representing a weak ETag for the configuration, as per RFC7232.
         This should not be set when creating a configuration, but may be set when updating a
         configuration. Default value is None.
        :type if_match: str
        :keyword content_type: Body Parameter content-type. Content type parameter for JSON body.
         Default value is "application/json".
        :paramtype content_type: str
        :return: Configuration or the result of cls(response)
        :rtype: ~azure.iot.hub.protocol.models.Configuration
        :raises ~azure.core.exceptions.HttpResponseError:
        """

    @overload
    async def create_or_update(
        self,
        id: str,
        configuration: IO[bytes],
        if_match: Optional[str] = None,
        *,
        content_type: str = "application/json",
        **kwargs: Any
    ) -> _models.Configuration:
        """Creates or updates a configuration on the IoT Hub for automatic device/module management.
        Configuration identifier and Content cannot be updated.

        :param id: The unique identifier of the configuration. Required.
        :type id: str
        :param configuration: The configuration to be created or updated. Required.
        :type configuration: IO[bytes]
        :param if_match: The string representing a weak ETag for the configuration, as per RFC7232.
         This should not be set when creating a configuration, but may be set when updating a
         configuration. Default value is None.
        :type if_match: str
        :keyword content_type: Body Parameter content-type. Content type parameter for binary body.
         Default value is "application/json".
        :paramtype content_type: str
        :return: Configuration or the result of cls(response)
        :rtype: ~azure.iot.hub.protocol.models.Configuration
        :raises ~azure.core.exceptions.HttpResponseError:
        """

    @distributed_trace_async
    async def create_or_update(
        self,
        id: str,
        configuration: Union[_models.Configuration, IO[bytes]],
        if_match: Optional[str] = None,
        **kwargs: Any
    ) -> _models.Configuration:
        """Creates or updates a configuration on the IoT Hub for automatic device/module management.
        Configuration identifier and Content cannot be updated.

        :param id: The unique identifier of the configuration. Required.
        :type id: str
        :param configuration: The configuration to be created or updated. Is either a Configuration
         type or a IO[bytes] type. Required.
        :type configuration: ~azure.iot.hub.protocol.models.Configuration or IO[bytes]
        :param if_match: The string representing a weak ETag for the configuration, as per RFC7232.
         This should not be set when creating a configuration, but may be set when updating a
         configuration. Default value is None.
        :type if_match: str
        :return: Configuration or the result of cls(response)
        :rtype: ~azure.iot.hub.protocol.models.Configuration
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
        _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

        api_version: str = kwargs.pop("api_version", _params.pop("api-version", self._config.api_version))
        content_type: Optional[str] = kwargs.pop("content_type", _headers.pop("Content-Type", None))
        cls: ClsType[_models.Configuration] = kwargs.pop("cls", None)

        content_type = content_type or "application/json"
        _json = None
        _content = None
        if isinstance(configuration, (IOBase, bytes)):
            _content = configuration
        else:
            _json = self._serialize.body(configuration, "Configuration")

        _request = build_create_or_update_request(
            id=id,
            if_match=if_match,
            api_version=api_version,
            content_type=content_type,
            json=_json,
            content=_content,
            headers=_headers,
            params=_params,
        )
        _request.url = self._client.format_url(_request.url)

        _stream = False
        pipeline_response: PipelineResponse = await self._client._pipeline.run(  # pylint: disable=protected-access
            _request, stream=_stream, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200, 201]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        deserialized = self._deserialize("Configuration", pipeline_response.http_response)

        if cls:
            return cls(pipeline_response, deserialized, {})  # type: ignore

        return deserialized  # type: ignore

    @distributed_trace_async
    async def delete(self, id: str, if_match: Optional[str] = None, **kwargs: Any) -> None:
        """Deletes a configuration on the IoT Hub for automatic device/module management.

        :param id: The unique identifier of the configuration. Required.
        :type id: str
        :param if_match: The string representing a weak ETag for the configuration, as per RFC7232. The
         delete operation is performed only if this ETag matches the value maintained by the server,
         indicating that the configuration has not been modified since it was last retrieved. To force
         an unconditional delete, set If-Match to the wildcard character (*). Default value is None.
        :type if_match: str
        :return: None or the result of cls(response)
        :rtype: None
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = kwargs.pop("headers", {}) or {}
        _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

        api_version: str = kwargs.pop("api_version", _params.pop("api-version", self._config.api_version))
        cls: ClsType[None] = kwargs.pop("cls", None)

        _request = build_delete_request(
            id=id,
            if_match=if_match,
            api_version=api_version,
            headers=_headers,
            params=_params,
        )
        _request.url = self._client.format_url(_request.url)

        _stream = False
        pipeline_response: PipelineResponse = await self._client._pipeline.run(  # pylint: disable=protected-access
            _request, stream=_stream, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [204]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        if cls:
            return cls(pipeline_response, None, {})  # type: ignore

    @distributed_trace_async
    async def get_configurations(self, top: Optional[int] = None, **kwargs: Any) -> list[_models.Configuration]:
        """Gets configurations on the IoT Hub for automatic device/module management. Pagination is not
        supported.

        :param top: The number of configurations to retrieve. Value will be overridden if greater than
         the maximum deployment count for the IoT Hub. Default value is None.
        :type top: int
        :return: list of Configuration or the result of cls(response)
        :rtype: list[~azure.iot.hub.protocol.models.Configuration]
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = kwargs.pop("headers", {}) or {}
        _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

        api_version: str = kwargs.pop("api_version", _params.pop("api-version", self._config.api_version))
        cls: ClsType[list[_models.Configuration]] = kwargs.pop("cls", None)

        _request = build_get_configurations_request(
            top=top,
            api_version=api_version,
            headers=_headers,
            params=_params,
        )
        _request.url = self._client.format_url(_request.url)

        _stream = False
        pipeline_response: PipelineResponse = await self._client._pipeline.run(  # pylint: disable=protected-access
            _request, stream=_stream, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        deserialized = self._deserialize("[Configuration]", pipeline_response.http_response)

        if cls:
            return cls(pipeline_response, deserialized, {})  # type: ignore

        return deserialized  # type: ignore

    @overload
    async def test_queries(
        self, input: _models.ConfigurationQueriesTestInput, *, content_type: str = "application/json", **kwargs: Any
    ) -> _models.ConfigurationQueriesTestResponse:
        """Validates target condition and custom metric queries for a configuration on the IoT Hub.

        :param input: The configuration for target condition and custom metric queries. Required.
        :type input: ~azure.iot.hub.protocol.models.ConfigurationQueriesTestInput
        :keyword content_type: Body Parameter content-type. Content type parameter for JSON body.
         Default value is "application/json".
        :paramtype content_type: str
        :return: ConfigurationQueriesTestResponse or the result of cls(response)
        :rtype: ~azure.iot.hub.protocol.models.ConfigurationQueriesTestResponse
        :raises ~azure.core.exceptions.HttpResponseError:
        """

    @overload
    async def test_queries(
        self, input: IO[bytes], *, content_type: str = "application/json", **kwargs: Any
    ) -> _models.ConfigurationQueriesTestResponse:
        """Validates target condition and custom metric queries for a configuration on the IoT Hub.

        :param input: The configuration for target condition and custom metric queries. Required.
        :type input: IO[bytes]
        :keyword content_type: Body Parameter content-type. Content type parameter for binary body.
         Default value is "application/json".
        :paramtype content_type: str
        :return: ConfigurationQueriesTestResponse or the result of cls(response)
        :rtype: ~azure.iot.hub.protocol.models.ConfigurationQueriesTestResponse
        :raises ~azure.core.exceptions.HttpResponseError:
        """

    @distributed_trace_async
    async def test_queries(
        self, input: Union[_models.ConfigurationQueriesTestInput, IO[bytes]], **kwargs: Any
    ) -> _models.ConfigurationQueriesTestResponse:
        """Validates target condition and custom metric queries for a configuration on the IoT Hub.

        :param input: The configuration for target condition and custom metric queries. Is either a
         ConfigurationQueriesTestInput type or a IO[bytes] type. Required.
        :type input: ~azure.iot.hub.protocol.models.ConfigurationQueriesTestInput or IO[bytes]
        :return: ConfigurationQueriesTestResponse or the result of cls(response)
        :rtype: ~azure.iot.hub.protocol.models.ConfigurationQueriesTestResponse
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
        _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

        api_version: str = kwargs.pop("api_version", _params.pop("api-version", self._config.api_version))
        content_type: Optional[str] = kwargs.pop("content_type", _headers.pop("Content-Type", None))
        cls: ClsType[_models.ConfigurationQueriesTestResponse] = kwargs.pop("cls", None)

        content_type = content_type or "application/json"
        _json = None
        _content = None
        if isinstance(input, (IOBase, bytes)):
            _content = input
        else:
            _json = self._serialize.body(input, "ConfigurationQueriesTestInput")

        _request = build_test_queries_request(
            api_version=api_version,
            content_type=content_type,
            json=_json,
            content=_content,
            headers=_headers,
            params=_params,
        )
        _request.url = self._client.format_url(_request.url)

        _stream = False
        pipeline_response: PipelineResponse = await self._client._pipeline.run(  # pylint: disable=protected-access
            _request, stream=_stream, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        deserialized = self._deserialize("ConfigurationQueriesTestResponse", pipeline_response.http_response)

        if cls:
            return cls(pipeline_response, deserialized, {})  # type: ignore

        return deserialized  # type: ignore

    @overload
    async def apply_on_edge_device(
        self, id: str, content: _models.ConfigurationContent, *, content_type: str = "application/json", **kwargs: Any
    ) -> None:
        """Applies the configuration content to an edge device.

        :param id: The unique identifier of the edge device. Required.
        :type id: str
        :param content: The configuration content. Required.
        :type content: ~azure.iot.hub.protocol.models.ConfigurationContent
        :keyword content_type: Body Parameter content-type. Content type parameter for JSON body.
         Default value is "application/json".
        :paramtype content_type: str
        :return: None or the result of cls(response)
        :rtype: None
        :raises ~azure.core.exceptions.HttpResponseError:
        """

    @overload
    async def apply_on_edge_device(
        self, id: str, content: IO[bytes], *, content_type: str = "application/json", **kwargs: Any
    ) -> None:
        """Applies the configuration content to an edge device.

        :param id: The unique identifier of the edge device. Required.
        :type id: str
        :param content: The configuration content. Required.
        :type content: IO[bytes]
        :keyword content_type: Body Parameter content-type. Content type parameter for binary body.
         Default value is "application/json".
        :paramtype content_type: str
        :return: None or the result of cls(response)
        :rtype: None
        :raises ~azure.core.exceptions.HttpResponseError:
        """

    @distributed_trace_async
    async def apply_on_edge_device(
        self, id: str, content: Union[_models.ConfigurationContent, IO[bytes]], **kwargs: Any
    ) -> None:
        """Applies the configuration content to an edge device.

        :param id: The unique identifier of the edge device. Required.
        :type id: str
        :param content: The configuration content. Is either a ConfigurationContent type or a IO[bytes]
         type. Required.
        :type content: ~azure.iot.hub.protocol.models.ConfigurationContent or IO[bytes]
        :return: None or the result of cls(response)
        :rtype: None
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
        _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

        api_version: str = kwargs.pop("api_version", _params.pop("api-version", self._config.api_version))
        content_type: Optional[str] = kwargs.pop("content_type", _headers.pop("Content-Type", None))
        cls: ClsType[None] = kwargs.pop("cls", None)

        content_type = content_type or "application/json"
        _json = None
        _content = None
        if isinstance(content, (IOBase, bytes)):
            _content = content
        else:
            _json = self._serialize.body(content, "ConfigurationContent")

        _request = build_apply_on_edge_device_request(
            id=id,
            api_version=api_version,
            content_type=content_type,
            json=_json,
            content=_content,
            headers=_headers,
            params=_params,
        )
        _request.url = self._client.format_url(_request.url)

        _stream = False
        pipeline_response: PipelineResponse = await self._client._pipeline.run(  # pylint: disable=protected-access
            _request, stream=_stream, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [204]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        if cls:
            return cls(pipeline_response, None, {})  # type: ignore
