# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
from collections.abc import MutableMapping
from io import IOBase
from typing import Any, Callable, IO, Optional, TypeVar, Union, overload

from azure.core import AsyncPipelineClient
from azure.core.exceptions import (
    ClientAuthenticationError,
    HttpResponseError,
    ResourceExistsError,
    ResourceNotFoundError,
    ResourceNotModifiedError,
    map_error,
)
from azure.core.pipeline import PipelineResponse
from azure.core.rest import AsyncHttpResponse, HttpRequest
from azure.core.tracing.decorator_async import distributed_trace_async
from azure.core.utils import case_insensitive_dict

from ... import models as _models
from ..._utils.serialization import Deserializer, Serializer
from ...operations._query_operations import build_get_twins_request
from .._configuration import IotHubGatewayServiceAPIsConfiguration

T = TypeVar("T")
ClsType = Optional[Callable[[PipelineResponse[HttpRequest, AsyncHttpResponse], T, dict[str, Any]], Any]]


class QueryOperations:
    """
    .. warning::
        **DO NOT** instantiate this class directly.

        Instead, you should access the following operations through
        :class:`~azure.iot.hub.protocol.aio.IotHubGatewayServiceAPIs`'s
        :attr:`query` attribute.
    """

    models = _models

    def __init__(self, *args, **kwargs) -> None:
        input_args = list(args)
        self._client: AsyncPipelineClient = input_args.pop(0) if input_args else kwargs.pop("client")
        self._config: IotHubGatewayServiceAPIsConfiguration = input_args.pop(0) if input_args else kwargs.pop("config")
        self._serialize: Serializer = input_args.pop(0) if input_args else kwargs.pop("serializer")
        self._deserialize: Deserializer = input_args.pop(0) if input_args else kwargs.pop("deserializer")

    @overload
    async def get_twins(
        self,
        query_specification: _models.QuerySpecification,
        x_ms_continuation: Optional[str] = None,
        x_ms_max_item_count: Optional[str] = None,
        *,
        content_type: str = "application/json",
        **kwargs: Any
    ) -> list[_models.Twin]:
        """Query an IoT Hub to retrieve information regarding device twins using a SQL-like language. See
        https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-query-language for more information.
        Pagination is supported. This returns information about device twins only.

        :param query_specification: The query string. See
         https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-query-language for more information.
         Required.
        :type query_specification: ~azure.iot.hub.protocol.models.QuerySpecification
        :param x_ms_continuation: The continuation token used to get the next page of results. Default
         value is None.
        :type x_ms_continuation: str
        :param x_ms_max_item_count: The maximum number of items returned per page. The service may use
         a different value if the value specified is not acceptable. Default value is None.
        :type x_ms_max_item_count: str
        :keyword content_type: Body Parameter content-type. Content type parameter for JSON body.
         Default value is "application/json".
        :paramtype content_type: str
        :return: list of Twin or the result of cls(response)
        :rtype: list[~azure.iot.hub.protocol.models.Twin]
        :raises ~azure.core.exceptions.HttpResponseError:
        """

    @overload
    async def get_twins(
        self,
        query_specification: IO[bytes],
        x_ms_continuation: Optional[str] = None,
        x_ms_max_item_count: Optional[str] = None,
        *,
        content_type: str = "application/json",
        **kwargs: Any
    ) -> list[_models.Twin]:
        """Query an IoT Hub to retrieve information regarding device twins using a SQL-like language. See
        https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-query-language for more information.
        Pagination is supported. This returns information about device twins only.

        :param query_specification: The query string. See
         https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-query-language for more information.
         Required.
        :type query_specification: IO[bytes]
        :param x_ms_continuation: The continuation token used to get the next page of results. Default
         value is None.
        :type x_ms_continuation: str
        :param x_ms_max_item_count: The maximum number of items returned per page. The service may use
         a different value if the value specified is not acceptable. Default value is None.
        :type x_ms_max_item_count: str
        :keyword content_type: Body Parameter content-type. Content type parameter for binary body.
         Default value is "application/json".
        :paramtype content_type: str
        :return: list of Twin or the result of cls(response)
        :rtype: list[~azure.iot.hub.protocol.models.Twin]
        :raises ~azure.core.exceptions.HttpResponseError:
        """

    @distributed_trace_async
    async def get_twins(
        self,
        query_specification: Union[_models.QuerySpecification, IO[bytes]],
        x_ms_continuation: Optional[str] = None,
        x_ms_max_item_count: Optional[str] = None,
        **kwargs: Any
    ) -> list[_models.Twin]:
        """Query an IoT Hub to retrieve information regarding device twins using a SQL-like language. See
        https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-query-language for more information.
        Pagination is supported. This returns information about device twins only.

        :param query_specification: The query string. See
         https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-query-language for more information.
         Is either a QuerySpecification type or a IO[bytes] type. Required.
        :type query_specification: ~azure.iot.hub.protocol.models.QuerySpecification or IO[bytes]
        :param x_ms_continuation: The continuation token used to get the next page of results. Default
         value is None.
        :type x_ms_continuation: str
        :param x_ms_max_item_count: The maximum number of items returned per page. The service may use
         a different value if the value specified is not acceptable. Default value is None.
        :type x_ms_max_item_count: str
        :return: list of Twin or the result of cls(response)
        :rtype: list[~azure.iot.hub.protocol.models.Twin]
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
        _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

        api_version: str = kwargs.pop("api_version", _params.pop("api-version", self._config.api_version))
        content_type: Optional[str] = kwargs.pop("content_type", _headers.pop("Content-Type", None))
        cls: ClsType[list[_models.Twin]] = kwargs.pop("cls", None)

        content_type = content_type or "application/json"
        _json = None
        _content = None
        if isinstance(query_specification, (IOBase, bytes)):
            _content = query_specification
        else:
            _json = self._serialize.body(query_specification, "QuerySpecification")

        _request = build_get_twins_request(
            x_ms_continuation=x_ms_continuation,
            x_ms_max_item_count=x_ms_max_item_count,
            api_version=api_version,
            content_type=content_type,
            json=_json,
            content=_content,
            headers=_headers,
            params=_params,
        )
        _request.url = self._client.format_url(_request.url)

        _stream = False
        pipeline_response: PipelineResponse = await self._client._pipeline.run(  # pylint: disable=protected-access
            _request, stream=_stream, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        response_headers = {}
        response_headers["x-ms-item-type"] = self._deserialize("str", response.headers.get("x-ms-item-type"))
        response_headers["x-ms-continuation"] = self._deserialize("str", response.headers.get("x-ms-continuation"))

        deserialized = self._deserialize("[Twin]", pipeline_response.http_response)

        if cls:
            return cls(pipeline_response, deserialized, response_headers)  # type: ignore

        return deserialized  # type: ignore
